id: IEE99EF3C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T06:43:14+00:00'
last_modified: '2022-06-10T04:44:20.297698+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25059
  title: སངས་རྒྱས་ཆོས་ལུགས་ཀྱི་ལྟ་སྤྱོད་སྐོར་གོ་བདེར་བཤད་པ་ཕན་བདེ་རྒྱ་མཚོའི་གྲུ་གཟིངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0060':
      image_group_id: I1PD30299
      title: Volume 1 of sangs rgyas chos lugs kyi lta spyod skor go bder bshad pa
        phan bde rgya mtsho'i gru gzings
      total_pages: 124
      order: 1
      base_file: 0060.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
